apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-keycloakx
  namespace: keycloak
spec:
  template:
    spec:
      containers:
      - name: keycloak
        env:
        - name: KEYCLOAK_USER
          value: admin
        - name: KEYCLOAK_PASSWORD
          value: admin
        - name: KEYCLOAK_IMPORT
          value: /opt/keycloak/data/import/realm.json
        volumeMounts:
        - mountPath: /opt/keycloak/data/import
          name: demo-realm
          readOnly: true
        - name: login-theme
          mountPath: /opt/jboss/keycloak/themes/keycloak/login/resources/css/
      volumes:
        - name: demo-realm
          configMap:
            name: demo-realm
            defaultMode: 365
            items:
              - key: realm.json
                path: realm.json
        - name: login-theme
          configMap:
            name: login-theme
            defaultMode: 0555